Add first files of data pipeline
src-d/shell-complete pull request #1
Opened 2017-07-07 10:46 UTC by warenlg

2017-07-10 10:09 UTC, vmarkovtsev requested changes

2017-07-10 10:09 UTC, vmarkovtsev commented on README.md
> +## Pase 1 : Build data pipeline
Phase

2017-07-10 10:09 UTC, vmarkovtsev commented on get_files.py
> +        for num, link in enumerate(f.readlines()):
for num, link in enumerate(f):

2017-07-10 10:09 UTC, vmarkovtsev commented on get_files.py
> +            html = requests.get(link).text
Please use [scrapy](https://scrapy.org/)

2017-07-19 18:38 UTC, vmarkovtsev requested changes

2017-07-19 18:38 UTC, vmarkovtsev commented on README.md
> +### Initialization
Installation

2017-07-19 18:38 UTC, vmarkovtsev commented on library.md
> +
Why newline here? If you want to mark this, use smth after * but before the link

2017-07-19 18:38 UTC, vmarkovtsev commented on setup.py
> +      )
Please remove this and add in the next PR. Packaging will be in the future.

2017-07-19 18:38 UTC, vmarkovtsev commented on requirements.txt
> +scrapy
requirements always have fixed or almost fixed versions. I recommend using fixed versions unless you really know the packages well.

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/__main__.py
> +        help="path to the output file")
Please always start help with a capital letter and end with a dot

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +    def write1file(self, path_to_file, output):
Better `write_file`

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +                lines = f.readlines()
```
for line in f:
    ...
```

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +            f.close()
Never `close()` if you use `with`. `close()` is used in the following case:

```
f = open(...)
try:
    # work with f
except:
    f.close()
```

`with` is a nice wrapper for this try-except. Further read: https://stackoverflow.com/questions/1984325/explaining-pythons-enter-and-exit

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +            print("--------------------------")
logging please

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +    Nb_file=0
Style: never start a variable or a method from a capital letter

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/corpus.py
> +            write_f.write1file(path_to_file, args.output)
OK, now I see. You don't need a class for this single op, do you?

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +class Zsh(object):
You seem to have several classes with the same interface. Please extract the interface.

```
class Shell:
    def existing_timestamps(seld, file_name):
        raise NotImplementedError
    ...

class Zsh(Shell):
    ...
```

P.S. Do not inherit from `object`. This is needed to be compatible with python 2.6 and later - we fix to >=3.4

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +    def existing_timestamps(seld, file_name):
Always name your methods as verbs (or looking as verbs). `detect_timestamps` or `timestamps_exist` better

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +        Return 1 if there are timestamps to remove in zsh file_name
We are coding in Python, not C/C++ - return a `bool`

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            lines = f.readlines()
del

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            test = re.match(timestamp, lines[0])
return re.match(timestamp, f.readline())

Use `re.compile` and cache the regexp as a static variable.

```
class Zsh:
    TIMESTAMP_RE = re.compile(<your string here>)

    def ...:
        return self.TIMESTAMP_RE.match(f.readline())
```

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +                command = re.split(timestamp, line)
same here - reuse the precompiled regexp

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            pattern = r"- cmd: "
set this pattern as a static variable

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            lines = f.readlines()
del

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            test = pattern in lines[0]
`readline()`

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            pattern = r"- cmd: "
reuse the static var here

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +            if f.endswith("zsh_history"):
Use static vars from the classes.

```
__shells__ = []

def register_shell(cls):
    __shells__.append(cls)
    return cls

class Shell:
    @classmethod
    def matches(cls, file_name):
        return file_name.endswith(cls.HISTORY_FILE)

@register_shell
class Zsh(Shell):
    HISTORY_FILE = "zsh_history"
    ...

...

for f in files:
    for cls in __shells__:
        if cls.matches(f):
            # use the public interface
```

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +                    fish_filtering.remove_timestamps(path_to_f)
Where is bash_history BTW?

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +class GithubShell(object):
GitHubShellDiscoverer

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +            print(num + 1, repos_fish[-1])
logging

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +        repos_fish = {x for x in repos_fish if x.endswith("/fish_history")}
You should not hardcode shells here but rather use HISTORY_FILE from your classes

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +        repos_fish = {x for x in repos_fish if x.endswith("/fish_history")}
And do not duplicate the code three times. Use `__shells__`

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +            time.sleep(0.7)
Hehe, wow! Why do you need this? At least put this into an instance variable (init in `__init__`), at max remove it.

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +        base = "https://raw.githubusercontent.com"
Make it a constant, move to a static var

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repos.py
> +        for rep in list(ens_repos):
You do not need to convert it to list if you just want to iterate. If you want the same order each time, use `sorted`

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/repospider.py
> +    f = open("repos.txt")
`with open() as f`
~close~

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/scrap/settings.py
> +BOT_NAME = 'scrap'
Give it a name

2017-07-19 18:38 UTC, vmarkovtsev commented on shcomplete/scrapy.cfg
> +project = scrap
Give it a name; remove the comments in `*.py` files except `settings.py`

2017-07-19 23:50 UTC, warenlg commented on shcomplete/filtering.py
> +                    fish_filtering.remove_timestamps(path_to_f)
no timestamps, seem to be all already clean

2017-07-20 06:03 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +                    fish_filtering.remove_timestamps(path_to_f)
https://askubuntu.com/questions/391082/how-to-see-time-stamps-in-bash-history

2017-07-24 12:14 UTC, closed without merging