Phase 1 : data pipeline
src-d/shell-complete pull request #2
Opened 2017-07-24 13:12 UTC by warenlg

2017-07-24 20:20 UTC, vmarkovtsev commented
@warenlg You overwrote my merge. You should not import modelforge through GitHub anymore. Instead, use `modelforge>=0.1.0-alpha`

2017-07-26 09:29 UTC, EgorBu requested changes
Everything looks good except:
* some quotes ('' -> "")
* magic variables (including `level=logging.INFO` - it should be defined by user)
* docstrings

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/__main__.py
> +    # tokens_parser = subparsers.add_parser("tokens",
Please remove commented code.

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/__main__.py
> +        "-i", "--token", required=True,
maybe '-t'?

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/corpus.py
> +def write_file(args, path_to_file):
I think it can be useful to add a parameter like "line_delimiter" that will be used to split lines. Just you can make default value equal to " ".

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/corpus.py
> +    logging.basicConfig(filename='corpus.log', level=logging.INFO)
* quotes '' -> ""
* magic value "corpus.log" - make constant or pass as a parameter to function
* logging level - it should be an argument

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/corpus.py
> +def write_file(args, path_to_file):
docstrings here and everywhere below)
function description, parameters, return, etc.

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/filtering.py
> +    def matches(self, file_name):
in the case of a class method:
`self` -> `cls`

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/filtering.py
> +    for root, d, files in os.walk("shcomplete/data"):
magic variable "shcomplete/data"

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/repos.py
> +class Shell:
it's the same class name as in shcomplete/filtering.py - has to be changed.

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/repos.py
> +            filename='shcomplete/repos.log', level=logging.INFO)
* quotes
* magic variable

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/repos.py
> +    with open("shcomplete/repos.txt", "w") as f:
* magic variable

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/repos.py
> +            f.write(rep + '\n')
* quotes

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/shell_scraper/items.py
> +import scrapy
Do you really need this file?

2017-07-26 09:29 UTC, EgorBu commented on shcomplete/corpus.py
> +    for root, d, files in os.walk("shcomplete/data"):
one more magic value)

2017-07-27 07:18 UTC, vmarkovtsev commented
@warenlg Please fix the review and Travis ASAP

2017-07-27 11:05 UTC, warenlg commented on shcomplete/shell_scraper/items.py
> +import scrapy
Yes, I think I need it

2017-07-27 15:22 UTC, vmarkovtsev requested changes

2017-07-27 15:22 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +class Shell_Timestamp:
No underscore in class names allowed

2017-08-01 10:52 UTC, vmarkovtsev requested changes
Almost there, just a few minor things, do not squash this time please

2017-08-01 10:52 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +class Zsh(ShellTimestamp):
ZshTimestamp

2017-08-01 10:52 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +class Fish(ShellTimestamp):
FishTimestamp

2017-08-01 10:52 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +class Bash(ShellTimestamp):
BashTimestamp

2017-08-01 10:52 UTC, vmarkovtsev commented on shcomplete/filtering.py
> +                   cls.detect_timestamps(path_to_file)):
Leave it on the previous line - 99 char limit should be enough

2017-08-01 12:20 UTC, merged